### ISSUE TITLE
RPI1 support

### ISSUE THREAD

**Issue by jyme** [ovh/overthebox#173]
Hi,

I see it's possible to works overthebox on a rpi 1 :D. But impossible to build correctly an image or download it with your link.

Do you think is it possible to explain me how have you done or reupload your build ? :).

Thank you

_Originally posted by @jyme in https://github.com/ovh/overthebox/issues/124#issuecomment-457500929_

**Comment by angt** [comment]
Hi,
Did you try with a config like ?
```
CONFIG_TARGET_brcm2708=y
CONFIG_TARGET_brcm2708_bcm2708=y
CONFIG_TARGET_brcm2708_bcm2708_DEVICE_rpi=y
```

**Comment by jyme** [comment]
Thank you for your response 👍.

I'm going to try.

**Comment by Adorfer** [comment]
just as a side remark: Please be prepared to obtain net bandwidth of 5-12MBit/s. 

(From my experiments with Openvpn, Fastd and Wireguard: 
Any type of performance orientated udp networking is impractical with current RPIs, due to the combination of USB interfacing and hardly any buffering/intelligence on the NIC. 
A discussion about bananaPi or other HW platforms with usable NICs would be a derail here)

**Comment by jyme** [comment]
I have tried this afternoon it was very long to compile my build but it has worked perfectly !!!

Thank you for your help @angt 

But I have an other problem now, i can see ip with command ifconfig, i can connect me with ssh but i can't to access to overthebox.ovh or with ip 192.168.100.1 i don't understand why :/.

Do you have an idea?

**Comment by angt** [comment]
I missed this one sorry :/
Please reopen an issue if it is still relevant.
